### ISSUE TITLE
this shit sucks!!

### ISSUE THREAD

**Issue by KittoniuM** [KaylinOwO/projectz#1]
get rid of it... WTF?

**Comment by KaylinOwO** [comment]
mad because your cheat doesnt have proper multi-game support and Rud wont suck you off anymore 

>:(

**Comment by KittoniuM** [comment]
proper multi game support?
rud sucking me off?

noob!! i own bigpackets - supports multi ENGINE while having the exact same ESP and Aimbot. get on my level!!

**Comment by KaylinOwO** [comment]
> proper multi game support?
> rud sucking me off?
> 
> noob!! i own bigpackets - supports multi ENGINE while having the exact same ESP and Aimbot. get on my level!!

it's funny, I just said that to get you mad and you did, nice one dude, get baited, you're just another 3rd worlder who thinks he's god, fuck off.

**Comment by KittoniuM** [comment]
> 
> 
> > proper multi game support?
> > rud sucking me off?
> > noob!! i own bigpackets - supports multi ENGINE while having the exact same ESP and Aimbot. get on my level!!
> 
> it's funny, I just said that to get you mad and you did, nice one dude, get baited, you're just another 3rd worlder who thinks he's god, fuck off.

ur the one releasing hacks to github

**Comment by KaylinOwO** [comment]
> > > proper multi game support?
> > > rud sucking me off?
> > > noob!! i own bigpackets - supports multi ENGINE while having the exact same ESP and Aimbot. get on my level!!
> > 
> > 
> > it's funny, I just said that to get you mad and you did, nice one dude, get baited, you're just another 3rd worlder who thinks he's god, fuck off.
> 
> ur the one releasing hacks to github

https://github.com/KittoniuM/win200 hello????????

**Comment by Shaxzy** [comment]
damn b1g boi

**Comment by KittoniuM** [comment]
uh oh! attacked by poop-coder nubs...

**Comment by KaylinOwO** [comment]
The amount of irony in that statement is unbelievable.

**Comment by KittoniuM** [comment]
u r not poop-coder?

**Comment by KaylinOwO** [comment]
The irony was that you're the "poop-coder", no one likes you or your shitty GMod cheat, it's a dead game.

**Comment by LordKara** [comment]
KittoniuM, the people you call your friends are only interested in your dogshit cheat. I hate to be the one to tell you this, but you're a joke, and that's coming from me, one of the most hated people in the cheating community. You should reconsider whatever decisions led you to comment here, because you have no pull, no power, nothing.

**Comment by KittoniuM** [comment]
LOL! mad poop-coder nub cuz cant make framework that can support 22 different games!!

**Comment by KittoniuM** [comment]
"KaylinOwO" is just skid who thinks he can get the attention of legits by releasing darkstorm paste. epic fail! brain erro xDD

**Comment by LordKara** [comment]
You're making a fool of yourself. Do you even care? Where's your dignity, red?

**Comment by KittoniuM** [comment]
> 
> 
> You're making a fool of yourself. Do you even care? Where's your dignity, red?

xDDD random non-coder trying to talk to superior super-coder!!
bow down pls or i will have 2 put u in ur cage..

**Comment by KittoniuM** [comment]
sure is,

**for (int i = 0; i < count; i++)
	{
		if (i == count - 1)
continue;**


did u make this as a course project or something LOL

**Comment by KittoniuM** [comment]
im dun arguing with nubz who managed to make their own tf2 hag, i hope u get starred xDDD

**Comment by KaylinOwO** [comment]
ok, have fun working on a cheat a game that's somehow deader than TF2.

**Comment by LordKara** [comment]
What's the point you're trying to make here? Yes, you're a better programmer. You have more experience. That's an obvious fact. Yes, we are new to programming, but we're gaining experience every day. However, clearly, you lack experience in the social department. Programming expertise can't make up for social retardation. Get some friends, or a boyfriend. Maybe then you won't be bothering people at 12 am.

**Comment by Aspect12** [comment]
U h .
